'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property back_bytt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back bytt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Drop_down_Arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drop down Arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Drop_down_book() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drop down book", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property drop_down_book2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drop down book2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Factors_Standard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Factors Standard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Factors_Standard1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Factors Standard1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Grade_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grade 8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Grade_8_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grade 8.2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property horizontal_straight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("horizontal straight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Savvy_Leaning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Savvy Leaning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Savvy_main_menu_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Savvy main menu logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel_grade_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel grade 8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel_grade_81() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel grade 81", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel_grade_82() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel grade 82", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel_grade_83() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel grade 83", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel_grade_84() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel grade 84", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel_grade_85() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel grade 85", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel_grade_86() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel grade 86", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Side_panel3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side panel3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms_and_factors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms and factors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms_and_factors_clicked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms and factors clicked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms_and_factors_Standard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms and factors Standard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms_and_factors1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms and factors1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms_clicked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms clicked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms_JPEG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms JPEG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms_JPEG1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms JPEG1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms_JPEG2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms JPEG2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms_JPEG3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms JPEG3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms_standard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms standard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Terms1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terms1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vertical_line() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vertical line", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
